"""STRIDE v1 loss components and ledgers.

This package follows the three-block objective frozen in
``docs/stride_design_freeze.md`` and ``docs/api_specs.md``: fit, prior, and
cohort losses remain separate until ``assembly`` combines them for the
optimizer.
"""
from __future__ import annotations

from .assembly import (
    ABLATION_MODES,
    ABLATION_TERM_HANDLING,
    EPSILON_NORM,
    GEOMETRY_EFFECTIVE_WEIGHT,
    NUMERICAL_MIN_MASS,
    OBJECTIVE_CONTRACT_VERSION,
    OFFDIAG_INIT_MASS,
    RHO_SUBBAG,
    S_COHORT,
    ADEState,
    CohortLossLedger,
    ConsistencyPatientLedger,
    EvidenceBlock,
    FovCostScale,
    LogitState,
    LossComponent,
    LossLedger,
    LossTotals,
    ObservationBlockLedger,
    ObjectiveContext,
    ScaleInit,
    assemble_loss_totals,
    compute_consistency_raw_from_block_losses,
    compute_geometry_raw,
    compute_init_fov_cost_scale,
    compute_loss_ledger,
    compute_open_raw,
    compute_recurrence_raw,
    identity_plus_small_open_initialization,
    parameters_from_unconstrained,
    post_reconstruct,
    unconstrained_from_constrained,
    unconstrained_from_initialization,
)

__all__ = [
    "ABLATION_MODES",
    "ABLATION_TERM_HANDLING",
    "EPSILON_NORM",
    "GEOMETRY_EFFECTIVE_WEIGHT",
    "NUMERICAL_MIN_MASS",
    "OBJECTIVE_CONTRACT_VERSION",
    "OFFDIAG_INIT_MASS",
    "RHO_SUBBAG",
    "S_COHORT",
    "ADEState",
    "CohortLossLedger",
    "ConsistencyPatientLedger",
    "EvidenceBlock",
    "FovCostScale",
    "LogitState",
    "LossComponent",
    "LossLedger",
    "LossTotals",
    "ObservationBlockLedger",
    "ObjectiveContext",
    "ScaleInit",
    "assemble_loss_totals",
    "compute_consistency_raw_from_block_losses",
    "compute_geometry_raw",
    "compute_init_fov_cost_scale",
    "compute_loss_ledger",
    "compute_open_raw",
    "compute_recurrence_raw",
    "identity_plus_small_open_initialization",
    "parameters_from_unconstrained",
    "post_reconstruct",
    "unconstrained_from_constrained",
    "unconstrained_from_initialization",
]
