"""Frozen Task A engineering contracts for the current active Task A surface.

This module is the machine-readable source of truth for the *active* Task A
surface responsibilities, execution order, and artifact expectations. The
scientific Block 3 contract still lives in the docs hierarchy, but the polluted
local Block 3 engineering surface was removed from the active path and is not
enumerated here as an executable contract.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .artifact_states import (
    CONTRACT_PASSED_STATE,
    EVIDENCE_READY_STATE,
    SCAFFOLD_ACTIVE_STATE,
)


SURFACE_EXECUTION_STATUS: frozenset[str] = frozenset(
    {"executable", "scaffold_only", "helper_only"}
)
GRAPH_EXECUTION_STATUS: frozenset[str] = frozenset(
    {"executable", "scaffold_only", "blocked_by_deferred_surface"}
)
READINESS_CLASSIFICATIONS: frozenset[str] = frozenset(
    {SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE, EVIDENCE_READY_STATE}
)


@dataclass(frozen=True)
class TaskASurfaceSpec:
    name: str
    owner: str
    kind: str
    consumes: tuple[str, ...]
    produces: tuple[str, ...]
    emitted_artifact_states: tuple[str, ...]
    execution_status: str
    does_not_do: tuple[str, ...]

    def to_json_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "owner": self.owner,
            "kind": self.kind,
            "consumes": list(self.consumes),
            "produces": list(self.produces),
            "emitted_artifact_states": list(self.emitted_artifact_states),
            "execution_status": self.execution_status,
            "does_not_do": list(self.does_not_do),
        }


@dataclass(frozen=True)
class TaskAExecutionNode:
    name: str
    surface_name: str
    canonical_order: int
    canonical_predecessors: tuple[str, ...]
    hard_prerequisites: tuple[str, ...]
    produced_artifacts: tuple[str, ...]
    execution_status: str
    blocker_reason: str | None = None

    def to_json_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "name": self.name,
            "surface_name": self.surface_name,
            "canonical_order": self.canonical_order,
            "canonical_predecessors": list(self.canonical_predecessors),
            "hard_prerequisites": list(self.hard_prerequisites),
            "produced_artifacts": list(self.produced_artifacts),
            "execution_status": self.execution_status,
        }
        if self.blocker_reason is not None:
            payload["blocker_reason"] = self.blocker_reason
        return payload


@dataclass(frozen=True)
class TaskAArtifactSpec:
    name: str
    filename: str
    producer: str
    purpose: str
    minimum_fields: tuple[str, ...]
    artifact_state_location: str
    allowed_artifact_states: tuple[str, ...]
    readiness_classification: str
    does_not_mean: tuple[str, ...]

    def to_json_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "filename": self.filename,
            "producer": self.producer,
            "purpose": self.purpose,
            "minimum_fields": list(self.minimum_fields),
            "artifact_state_location": self.artifact_state_location,
            "allowed_artifact_states": list(self.allowed_artifact_states),
            "readiness_classification": self.readiness_classification,
            "does_not_mean": list(self.does_not_mean),
        }


TASK_A_SURFACE_SPECS: tuple[TaskASurfaceSpec, ...] = (
    TaskASurfaceSpec(
        name="build_stage0_artifacts",
        owner="tasks.task_A.stage0.build_artifacts",
        kind="builder",
        consumes=("CRLM cohort RDS", "Stage 0 build parameters"),
        produces=("task_A_stage0_k{K}.h5ad", "task_A_stage0_validation.json"),
        emitted_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        execution_status="executable",
        does_not_do=(
            "Run Step 1 prepare",
            "Run Block 0, Block 1, or Block 2",
            "Emit scientific evidence claims",
        ),
    ),
    TaskASurfaceSpec(
        name="check_task_a_pre_block0_data_suitability",
        owner="tasks.task_A.workflows.check_data_suitability",
        kind="report",
        consumes=("task-config", "stage0-h5ad", "output-dir"),
        produces=("task_a_pre_block0_data_suitability.json",),
        emitted_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        execution_status="executable",
        does_not_do=(
            "Downgrade semantic misalignment into a passing report",
            "Substitute for Block 0 passage",
            "Emit primary scientific evidence",
        ),
    ),
    TaskASurfaceSpec(
        name="prepare_task_a_stage0_mapping",
        owner="tasks.task_A.workflows.prepare",
        kind="runner",
        consumes=(
            "task-config",
            "stage0-h5ad",
            "output-dir",
            "optional patient-id selectors",
            "optional demo-subset selector",
        ),
        produces=(
            "task_a_stride_mapping.json",
            "task_a_core_fit_dry_run.csv",
            "task_a_prepare_manifest.json",
        ),
        emitted_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        execution_status="executable",
        does_not_do=(
            "Satisfy the Block 0 scientific gate",
            "Run block-local interpretation",
            "Create a shared task-global export index",
        ),
    ),
    TaskASurfaceSpec(
        name="write_task_a_descriptive_atlas",
        owner="tasks.task_A.descriptive",
        kind="runner",
        consumes=(
            "task-config",
            "stage0-h5ad",
            "output-dir",
            "optional patient-id selectors",
            "optional max-overlay-communities",
        ),
        produces=(
            "task_a_descriptive_atlas_manifest.json",
            "task_a_descriptive_atlas_output_index.csv",
            "descriptive atlas tables",
            "descriptive atlas figures",
        ),
        emitted_artifact_states=(),
        execution_status="executable",
        does_not_do=(
            "Consume Step 1 prepare artifacts as hard inputs",
            "Run Block 0, Block 1, or Block 2",
            "Emit confirmatory or inferential claims",
        ),
    ),
    TaskASurfaceSpec(
        name="run_block0_workflow",
        owner="tasks.task_A.workflows.run_block0",
        kind="runner",
        consumes=(
            "task-config",
            "stage0-h5ad",
            "output-dir",
            "optional patient-id selectors",
            "optional demo-subset selector",
        ),
        produces=("block0_bundle.json", "block0_pair_metrics.csv"),
        emitted_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        execution_status="executable",
        does_not_do=(
            "Read Step 1 files as hard inputs",
            "Emit interpretation prose",
            "Use observation-match-specific R/M gate metrics",
            "Promote subset or demo sidecars into a passing Block 0 bundle",
        ),
    ),
    TaskASurfaceSpec(
        name="write_task_a_block1_bundle",
        owner="tasks.task_A.block1.bundle",
        kind="runner",
        consumes=("task-config", "stage0-h5ad", "passed block0 bundle", "output-dir"),
        produces=(
            "block1_stage0_mapping.json",
            "block1_core_fit_dry_run.csv",
            "block1_family_summary.csv",
            "block1_source_community_summary.csv",
            "block1_target_community_summary.csv",
            "block1_confirmatory_family_comparison.csv",
            "block1_exploratory_source_community_comparison.csv",
            "block1_exploratory_target_community_comparison.csv",
            "community_correspondence/block1_community_correspondence_manifest.json",
            "community_correspondence/block1_community_correspondence_index.csv",
            "community_correspondence tables",
            "block1_bundle.json",
            "block1_workflow_manifest.json",
        ),
        emitted_artifact_states=(EVIDENCE_READY_STATE,),
        execution_status="executable",
        does_not_do=(
            "Implement Block 0",
            "Consume Step 1 files as hard inputs",
            "Change the legacy Block 1 compatibility identifier",
            "Promote supportive target-side summaries into direct emergence/disappearance proof",
            "Promote exploratory/supportive community comparisons into confirmatory claims",
        ),
    ),
    TaskASurfaceSpec(
        name="write_block2_bundle",
        owner="tasks.task_A.block2.bundle",
        kind="runner",
        consumes=("block1 bundle", "output-dir"),
        produces=(
            "block2_bounded_audit_summary.csv",
            "block2_contract_audit.csv",
            "block2_replicate_manifest.csv",
            "block2_family_robustness.csv",
            "block2_source_community_robustness.csv",
            "block2_target_community_robustness.csv",
            "block2_bounded_audit_manifest.json",
        ),
        emitted_artifact_states=(EVIDENCE_READY_STATE,),
        execution_status="executable",
        does_not_do=(
            "Run without evidence-ready Block 1 summary provenance",
            "Change the frozen Block 1 summary contract",
            "Compare baselines or run ablations",
            "Claim true disappearance or emergence",
        ),
    ),
    TaskASurfaceSpec(
        name="write_semisynthetic_artifacts",
        owner="tasks.task_A.benchmarks.semisynthetic",
        kind="exporter",
        consumes=("output-root", "manifest filename", "n_patients", "seed"),
        produces=("semisynthetic manifest CSV", "task_a_semisynthetic_contract.json"),
        emitted_artifact_states=(CONTRACT_PASSED_STATE,),
        execution_status="executable",
        does_not_do=(
            "Run the real-data Task A pipeline",
            "Substitute for Block 0 or Block 1 evidence",
            "Define new STRIDE core semantics",
        ),
    ),
    TaskASurfaceSpec(
        name="TaskADemoSubset registry",
        owner="tasks.task_A.real_data.demo_subset",
        kind="registry",
        consumes=("demo subset name",),
        produces=("prepare manifest provenance fields",),
        emitted_artifact_states=(),
        execution_status="helper_only",
        does_not_do=(
            "Store derived data artifacts",
            "Filter data outside the prepare workflow",
            "Define a new real-data runner",
        ),
    ),
    TaskASurfaceSpec(
        name="stride_adapter helpers",
        owner="tasks.task_A.workflows.stride_adapter",
        kind="adapter",
        consumes=("Stage 0 h5ad or AnnData", "Task A config bundle"),
        produces=("mapping summaries", "family-sliced observations", "dry-run records"),
        emitted_artifact_states=(),
        execution_status="helper_only",
        does_not_do=(
            "Write task-global manifests on its own",
            "Move Task A semantics into src/stride/",
            "Redefine the STRIDE core method",
        ),
    ),
    TaskASurfaceSpec(
        name="Task A contract helpers",
        owner="tasks.task_A.contracts",
        kind="contract_helper",
        consumes=("bundle/manfiest payloads",),
        produces=("artifact-state validation", "mapping schemas", "design freeze registry"),
        emitted_artifact_states=(),
        execution_status="helper_only",
        does_not_do=(
            "Execute experiments",
            "Interpret scientific results",
            "Expose task-specific APIs from src/stride/",
        ),
    ),
)


TASK_A_EXECUTION_GRAPH: tuple[TaskAExecutionNode, ...] = (
    TaskAExecutionNode(
        name="stage0_artifact_builder",
        surface_name="build_stage0_artifacts",
        canonical_order=0,
        canonical_predecessors=(),
        hard_prerequisites=("CRLM cohort RDS",),
        produced_artifacts=("task_A_stage0_k{K}.h5ad", "task_A_stage0_validation.json"),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="step1_prepare_full_cohort",
        surface_name="prepare_task_a_stage0_mapping",
        canonical_order=1,
        canonical_predecessors=("stage0_artifact_builder",),
        hard_prerequisites=("stage0-h5ad", "task-config"),
        produced_artifacts=(
            "task_a_stride_mapping.json",
            "task_a_core_fit_dry_run.csv",
            "task_a_prepare_manifest.json",
        ),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="descriptive_atlas_context_layer",
        surface_name="write_task_a_descriptive_atlas",
        canonical_order=2,
        canonical_predecessors=("stage0_artifact_builder",),
        hard_prerequisites=("stage0-h5ad", "task-config"),
        produced_artifacts=(
            "task_a_descriptive_atlas_manifest.json",
            "task_a_descriptive_atlas_output_index.csv",
            "descriptive atlas tables",
            "descriptive atlas figures",
        ),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="pre_block0_data_suitability_report",
        surface_name="check_task_a_pre_block0_data_suitability",
        canonical_order=3,
        canonical_predecessors=("stage0_artifact_builder",),
        hard_prerequisites=("stage0-h5ad", "task-config"),
        produced_artifacts=("task_a_pre_block0_data_suitability.json",),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="step1_prepare_subset_or_demo",
        surface_name="prepare_task_a_stage0_mapping",
        canonical_order=4,
        canonical_predecessors=("stage0_artifact_builder",),
        hard_prerequisites=("stage0-h5ad", "task-config", "patient-id or demo-subset"),
        produced_artifacts=(
            "task_a_stride_mapping.json",
            "task_a_core_fit_dry_run.csv",
            "task_a_prepare_manifest.json",
        ),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="block0_locality_gate",
        surface_name="run_block0_workflow",
        canonical_order=5,
        canonical_predecessors=("step1_prepare_full_cohort", "descriptive_atlas_context_layer"),
        hard_prerequisites=("stage0-h5ad", "task-config"),
        produced_artifacts=("block0_bundle.json", "block0_pair_metrics.csv"),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="block1_continuity_backbone",
        surface_name="write_task_a_block1_bundle",
        canonical_order=6,
        canonical_predecessors=(
            "step1_prepare_full_cohort",
            "descriptive_atlas_context_layer",
            "block0_locality_gate",
        ),
        hard_prerequisites=("stage0-h5ad", "task-config", "passed block0 bundle"),
        produced_artifacts=(
            "block1_stage0_mapping.json",
            "block1_core_fit_dry_run.csv",
            "block1_family_summary.csv",
            "block1_source_community_summary.csv",
            "block1_target_community_summary.csv",
            "block1_confirmatory_family_comparison.csv",
            "block1_exploratory_source_community_comparison.csv",
            "block1_exploratory_target_community_comparison.csv",
            "community_correspondence/block1_community_correspondence_manifest.json",
            "community_correspondence/block1_community_correspondence_index.csv",
            "community_correspondence tables",
            "block1_bundle.json",
            "block1_workflow_manifest.json",
        ),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="block2_bounded_audit",
        surface_name="write_block2_bundle",
        canonical_order=7,
        canonical_predecessors=("block1_continuity_backbone",),
        hard_prerequisites=("block1 bundle",),
        produced_artifacts=(
            "block2_bounded_audit_summary.csv",
            "block2_contract_audit.csv",
            "block2_replicate_manifest.csv",
            "block2_family_robustness.csv",
            "block2_source_community_robustness.csv",
            "block2_target_community_robustness.csv",
            "block2_bounded_audit_manifest.json",
        ),
        execution_status="executable",
    ),
    TaskAExecutionNode(
        name="semisynthetic_benchmark_export",
        surface_name="write_semisynthetic_artifacts",
        canonical_order=9,
        canonical_predecessors=(),
        hard_prerequisites=("benchmark settings",),
        produced_artifacts=("semisynthetic manifest CSV", "task_a_semisynthetic_contract.json"),
        execution_status="executable",
    ),
)


TASK_A_ARTIFACT_SPECS: tuple[TaskAArtifactSpec, ...] = (
    TaskAArtifactSpec(
        name="stage0_validation_report",
        filename="task_A_stage0_validation.json",
        producer="build_stage0_artifacts",
        purpose="Validate that a built Stage 0 h5ad satisfies the frozen Task A input contract.",
        minimum_fields=(
            "artifact_state",
            "taska_minimum_contract",
            "representation_completeness",
            "counts",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Step 1 alignment already passed",
            "Block 0 is passed",
        ),
    ),
    TaskAArtifactSpec(
        name="step1_stride_mapping",
        filename="task_a_stride_mapping.json",
        producer="prepare_task_a_stage0_mapping",
        purpose="Freeze the Stage 0 to STRIDE crosswalk and per-family eligibility summary.",
        minimum_fields=(
            "field_mapping",
            "patient_ids",
            "family_summaries",
            "real_data_crosswalk",
        ),
        artifact_state_location="task_a_prepare_manifest.json.artifact_state",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Block 0 gate is passed",
            "Block 1 evidence is ready",
        ),
    ),
    TaskAArtifactSpec(
        name="step1_core_fit_dry_run",
        filename="task_a_core_fit_dry_run.csv",
        producer="prepare_task_a_stage0_mapping",
        purpose="Record task-local dry-run bridge statuses for confirmatory pair families.",
        minimum_fields=(
            "pair_family",
            "claim_role",
            "patient_id",
            "fit_status",
            "bridge_realized",
            "defer_reason",
            "uncertainty_status",
            "source_domain",
            "target_domain",
        ),
        artifact_state_location="task_a_prepare_manifest.json.artifact_state",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Scientific interpretation is allowed",
            "A Block 0 bundle exists",
        ),
    ),
    TaskAArtifactSpec(
        name="step1_prepare_manifest",
        filename="task_a_prepare_manifest.json",
        producer="prepare_task_a_stage0_mapping",
        purpose="Declare Step 1 provenance, run scope, and readiness for the prepare surface.",
        minimum_fields=(
            "task_name",
            "config_path",
            "stage0_h5ad",
            "mapping_manifest",
            "core_fit_dry_run",
            "pair_families",
            "confirmatory_pair_families",
            "run_scope",
            "artifact_state",
            "block0_gate_status",
            "scientific_interpretation_allowed",
            "mass_mode",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Block 0 passage",
            "Primary Block 1 evidence",
        ),
    ),
    TaskAArtifactSpec(
        name="pre_block0_data_suitability_report",
        filename="task_a_pre_block0_data_suitability.json",
        producer="check_task_a_pre_block0_data_suitability",
        purpose="Summarize pre-Block 0 compatibility and semantic alignment readiness.",
        minimum_fields=(
            "task_name",
            "config_path",
            "stage0_h5ad",
            "report_scope",
            "run_scope",
            "artifact_state",
            "block0_gate_status",
            "scientific_interpretation_allowed",
            "mass_mode",
            "confirmatory_pair_families",
            "audit_pair_families",
            "stage0_validation",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Block 0 passage",
            "Primary evidence readiness",
        ),
    ),
    TaskAArtifactSpec(
        name="descriptive_atlas_manifest",
        filename="task_a_descriptive_atlas_manifest.json",
        producer="write_task_a_descriptive_atlas",
        purpose=(
            "Declare descriptive-atlas labeling, Stage 0 field keys, counts, "
            "and the indexed output surface."
        ),
        minimum_fields=(
            "workflow_name",
            "atlas_role",
            "claim_scope",
            "scientific_interpretation_allowed",
            "config_path",
            "stage0_h5ad",
            "community_id_key",
            "cell_subtype_key",
            "domain_key",
            "fov_key",
            "spatial_key",
            "configured_community_ids",
            "observed_community_ids",
            "output_index",
        ),
        artifact_state_location="none",
        allowed_artifact_states=(),
        readiness_classification="descriptive_only",
        does_not_mean=(
            "Block 0 passage",
            "Any confirmatory claim is justified",
            "Block 1 evidence is ready",
        ),
    ),
    TaskAArtifactSpec(
        name="descriptive_atlas_output_index",
        filename="task_a_descriptive_atlas_output_index.csv",
        producer="write_task_a_descriptive_atlas",
        purpose="Index the descriptive-atlas tables and figures written to the output directory.",
        minimum_fields=(
            "relative_path",
            "artifact_kind",
            "category",
            "format",
            "description",
        ),
        artifact_state_location="none",
        allowed_artifact_states=(),
        readiness_classification="descriptive_only",
        does_not_mean=(
            "Every listed file is inferential",
            "The atlas may substitute for Block 0 validation",
        ),
    ),
    TaskAArtifactSpec(
        name="block0_bundle_contract",
        filename="block0_bundle.json",
        producer="run_block0_workflow",
        purpose=(
            "Freeze Block 0 provenance, gate summaries, and pass/defer/fail state "
            "for the STRIDE-native real-vs-null TC-IM gate."
        ),
        minimum_fields=(
            "block",
            "status",
            "artifact_state",
            "run_scope",
            "block0_passed",
            "config_fingerprint",
            "config_path",
            "stage0_h5ad",
            "output_dir",
            "bundle_path",
            "pair_metrics_path",
            "real_families",
            "null_families",
            "pre_block0_data_suitability",
            "gate_checks",
            "metrics_summary",
            "failure_reasons",
            "inputs",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Subset or demo scope may pass Block 0",
            "Block 1 or Block 2 logic changed",
            "Block 1 or Block 2 semantics changed",
        ),
    ),
    TaskAArtifactSpec(
        name="block0_pair_metrics",
        filename="block0_pair_metrics.csv",
        producer="run_block0_workflow",
        purpose="Record one paired patient-level Block 0 real/null comparison row with STRIDE-native summaries.",
        minimum_fields=(
            "comparison_id",
            "run_scope",
            "pair_family",
            "null_family",
            "anchor_patient_id",
            "null_target_donor_patient_id",
            "source_domain",
            "target_domain",
            "n_source_observations",
            "n_target_observations",
            "count_stratum_key",
            "selection_seed",
            "null_assignment_status",
            "null_assignment_reason",
            "real_fit_status",
            "null_fit_status",
            "real_defer_reason",
            "null_defer_reason",
            "real_total_continuity_mass",
            "null_total_continuity_mass",
            "delta_total_continuity_mass",
            "real_total_depletion_mass",
            "null_total_depletion_mass",
            "delta_total_depletion_mass",
            "real_total_emergence_mass",
            "null_total_emergence_mass",
            "delta_total_emergence_mass",
        ),
        artifact_state_location="block0_bundle.json.artifact_state",
        allowed_artifact_states=(SCAFFOLD_ACTIVE_STATE, CONTRACT_PASSED_STATE),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "The Block 0 gate passed",
            "A deferred null assignment is acceptable for a passing full-cohort gate",
            "Observation-match R/M metrics drove the live Block 0 decision",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_family_summary",
        filename="block1_family_summary.csv",
        producer="write_task_a_block1_bundle",
        purpose="Freeze patient-level Block 1 family summaries on the frozen summary-name and scale axes.",
        minimum_fields=(
            "patient_id",
            "pair_family",
            "claim_role",
            "source_domain",
            "target_domain",
            "summary_name",
            "summary_role",
            "scale",
            "value",
            "eligible_entity_axis",
            "eligible_entity_count",
            "burden_total",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Block 2 robustness is complete",
            "Target-side supportive summaries became proof-carrying",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_source_community_summary",
        filename="block1_source_community_summary.csv",
        producer="write_task_a_block1_bundle",
        purpose="Freeze patient-level source-community Block 1 summaries including self-retention, depletion, remodeling, and top targets.",
        minimum_fields=(
            "patient_id",
            "pair_family",
            "claim_role",
            "source_domain",
            "target_domain",
            "source_community_id",
            "source_burden",
            "source_weight",
            "self_retention",
            "depletion",
            "off_diagonal_remodeling",
            "self_retention_burden",
            "depletion_burden",
            "off_diagonal_burden",
            "top_target_1_id",
            "top_target_1_value",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Neighborhood-based continuity was estimated",
            "Target-side emergence is confirmed",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_target_community_summary",
        filename="block1_target_community_summary.csv",
        producer="write_task_a_block1_bundle",
        purpose="Freeze patient-level target-community Block 1 summaries including incoming matched burden and supportive emergence.",
        minimum_fields=(
            "patient_id",
            "pair_family",
            "claim_role",
            "source_domain",
            "target_domain",
            "target_community_id",
            "target_burden",
            "target_weight",
            "incoming_matched_operator",
            "incoming_matched_burden",
            "emergence_tendency",
            "emergence_burden",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Emergence is proof-carrying in this pass",
            "Block 2 robustness is complete",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_stage0_mapping",
        filename="block1_stage0_mapping.json",
        producer="write_task_a_block1_bundle",
        purpose="Capture the Task A mapping summary used by the Block 1 evidence surface.",
        minimum_fields=(
            "field_mapping",
            "patient_ids",
            "family_summaries",
            "real_data_crosswalk",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "A new Step 1 contract was run",
            "Block 2 audit is complete",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_core_fit_dry_run",
        filename="block1_core_fit_dry_run.csv",
        producer="write_task_a_block1_bundle",
        purpose="Carry the confirmatory Block 1 dry-run realization context alongside the summary contract outputs.",
        minimum_fields=(
            "pair_family",
            "claim_role",
            "patient_id",
            "fit_status",
            "bridge_realized",
            "defer_reason",
            "uncertainty_status",
            "source_domain",
            "target_domain",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "True emergence or disappearance is proven",
            "Block 0 was implemented in this pass",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_confirmatory_family_comparison",
        filename="block1_confirmatory_family_comparison.csv",
        producer="write_task_a_block1_bundle",
        purpose="Freeze the patient-paired confirmatory `TC-IM` versus `TC-PT` comparison surface on the frozen Block 1 family summary axes.",
        minimum_fields=(
            "patient_id",
            "pair_family_left",
            "pair_family_right",
            "summary_name",
            "summary_role",
            "scale",
            "eligible_entity_axis",
            "tc_im_value",
            "tc_pt_value",
            "delta_tc_im_minus_tc_pt",
            "contrast_direction",
            "comparison_status",
            "comparison_scope_role",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Community-level outputs became confirmatory",
            "Block 2 robustness is complete",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_exploratory_source_community_comparison",
        filename="block1_exploratory_source_community_comparison.csv",
        producer="write_task_a_block1_bundle",
        purpose="Export the patient-paired exploratory/supportive source-community `TC-IM` versus `TC-PT` comparison surface.",
        minimum_fields=(
            "patient_id",
            "pair_family_left",
            "pair_family_right",
            "source_community_id",
            "summary_name",
            "summary_role",
            "tc_im_value",
            "tc_pt_value",
            "delta_tc_im_minus_tc_pt",
            "comparison_status",
            "comparison_scope_role",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "The source-community comparison is confirmatory",
            "Missing community rows imply fitting failed",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_exploratory_target_community_comparison",
        filename="block1_exploratory_target_community_comparison.csv",
        producer="write_task_a_block1_bundle",
        purpose="Export the patient-paired exploratory/supportive target-community `TC-IM` versus `TC-PT` comparison surface.",
        minimum_fields=(
            "patient_id",
            "pair_family_left",
            "pair_family_right",
            "target_community_id",
            "summary_name",
            "summary_role",
            "tc_im_value",
            "tc_pt_value",
            "delta_tc_im_minus_tc_pt",
            "comparison_status",
            "comparison_scope_role",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "The target-community comparison is confirmatory",
            "Emergence became proof-carrying in this pass",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_community_correspondence_manifest",
        filename="block1_community_correspondence_manifest.json",
        producer="write_task_a_block1_bundle",
        purpose="Declare the objective Block 1 community-correspondence packet and point to its machine-readable outputs.",
        minimum_fields=(
            "workflow_name",
            "packet_role",
            "scientific_interpretation_allowed",
            "artifact_state",
            "config_path",
            "stage0_h5ad",
            "community_id_key",
            "cell_subtype_key",
            "patient_id_key",
            "configured_state_ids",
            "observed_community_ids",
            "output_index",
        ),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Biological interpretation prose was added",
            "The packet substitutes for the primary Block 1 evidence surfaces",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_community_correspondence_index",
        filename="block1_community_correspondence_index.csv",
        producer="write_task_a_block1_bundle",
        purpose="Index the Block 1 community-correspondence packet tables and referenced summary surfaces in a machine-readable form.",
        minimum_fields=("relative_path", "artifact_kind", "category", "format", "description"),
        artifact_state_location="block1_bundle.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Every indexed surface is confirmatory",
            "The packet includes interpretation prose",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_bundle",
        filename="block1_bundle.json",
        producer="write_task_a_block1_bundle",
        purpose="Freeze Block 1 provenance, scientific role, compatibility block id, and summary-contract output paths.",
        minimum_fields=(
            "block",
            "scientific_role",
            "status",
            "artifact_state",
            "block0_bundle_path",
            "block0_gate_status",
            "config_fingerprint",
            "config_path",
            "stage0_h5ad",
            "output_dir",
            "mapping_manifest_path",
            "core_fit_dry_run_path",
            "family_summary_path",
            "source_community_summary_path",
            "target_community_summary_path",
            "confirmatory_family_comparison_path",
            "exploratory_source_community_comparison_path",
            "exploratory_target_community_comparison_path",
            "community_correspondence_manifest_path",
            "community_correspondence_index_path",
            "bundle_path",
            "pair_families",
            "confirmatory_pair_families",
            "summary_contract_version",
            "paired_comparison_contract_version",
            "proof_carrying_family_summaries",
            "supportive_family_summaries",
            "family_summary_scales",
            "source_eligibility_rule",
            "target_eligibility_rule",
            "fit_result_counts",
            "stage0_mapping",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Block 2 audit is complete",
            "A new Block 0 algorithm was introduced",
        ),
    ),
    TaskAArtifactSpec(
        name="block1_workflow_manifest",
        filename="block1_workflow_manifest.json",
        producer="write_task_a_block1_bundle",
        purpose="Provide a compact pointer manifest for the Block 1 summary contract output directory.",
        minimum_fields=(
            "block",
            "scientific_role",
            "status",
            "artifact_state",
            "block0_bundle_path",
            "block0_gate_status",
            "config_fingerprint",
            "bundle_path",
            "core_fit_dry_run_path",
            "mapping_manifest_path",
            "family_summary_path",
            "source_community_summary_path",
            "target_community_summary_path",
            "confirmatory_family_comparison_path",
            "exploratory_source_community_comparison_path",
            "exploratory_target_community_comparison_path",
            "community_correspondence_manifest_path",
            "community_correspondence_index_path",
            "summary_contract_version",
            "paired_comparison_contract_version",
            "proof_carrying_family_summaries",
            "supportive_family_summaries",
            "family_summary_scales",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "The full Block 1 bundle can be omitted",
            "Block 2 audit is embedded here",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_summary",
        filename="block2_bounded_audit_summary.csv",
        producer="write_block2_bundle",
        purpose="Summarize overall Block 2 robustness calls over the frozen Block 1 findings across the primary perturbation routes.",
        minimum_fields=(
            "block",
            "summary_scope",
            "finding_priority",
            "summary_name",
            "scale",
            "community_id",
            "full_data_direction",
            "primary_routes_executed",
            "primary_routes_robust",
            "overall_robustness_call",
        ),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "True emergence or disappearance is proven",
            "A baseline comparison or ablation was performed",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_replicate_manifest",
        filename="block2_replicate_manifest.csv",
        producer="write_block2_bundle",
        purpose="Record the executed Block 2 perturbation replicates, retained patient/ROI/cell counts, and replicate-level failures.",
        minimum_fields=(
            "route_name",
            "route_group",
            "replicate_index",
            "replicate_label",
            "selection_seed",
            "patient_subset_json",
            "dropped_roi_ids_json",
            "route_status",
            "failure_reason",
            "n_patients_retained",
            "n_rois_retained",
            "n_cells_retained",
        ),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "The replicate itself recovered a scientific finding",
            "Biological interpretation should be written at the replicate level",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_family_robustness",
        filename="block2_family_robustness.csv",
        producer="write_block2_bundle",
        purpose="Carry route-level robustness summaries for the frozen family-level Block 1 findings.",
        minimum_fields=(
            "block",
            "route_name",
            "route_group",
            "finding_id",
            "summary_scope",
            "finding_priority",
            "summary_name",
            "scale",
            "full_data_direction",
            "direction_recovery_rate",
            "estimable_replicate_fraction",
            "median_replicate_support_fraction",
            "robustness_call",
        ),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "The corresponding Block 1 family finding became confirmatory from scratch",
            "The robustness route is a baseline comparison",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_source_community_robustness",
        filename="block2_source_community_robustness.csv",
        producer="write_block2_bundle",
        purpose="Carry route-level robustness summaries for the scoped source-community Block 1 findings.",
        minimum_fields=(
            "block",
            "route_name",
            "route_group",
            "finding_id",
            "summary_scope",
            "finding_priority",
            "summary_name",
            "community_id",
            "full_data_direction",
            "direction_recovery_rate",
            "estimable_replicate_fraction",
            "median_replicate_support_fraction",
            "median_replicate_rank",
            "robustness_call",
        ),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "All source-community rows are equal-weight primary claims",
            "Community robustness substitutes for the family-level Block 1 evidence stack",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_target_community_robustness",
        filename="block2_target_community_robustness.csv",
        producer="write_block2_bundle",
        purpose="Carry route-level robustness summaries for the scoped target-community Block 1 findings.",
        minimum_fields=(
            "block",
            "route_name",
            "route_group",
            "finding_id",
            "summary_scope",
            "finding_priority",
            "summary_name",
            "community_id",
            "full_data_direction",
            "direction_recovery_rate",
            "estimable_replicate_fraction",
            "median_replicate_support_fraction",
            "median_replicate_rank",
            "robustness_call",
        ),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Target-community robustness proves true emergence/disappearance",
            "The route-level table is a method-comparison surface",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_contract_audit",
        filename="block2_contract_audit.csv",
        producer="write_block2_bundle",
        purpose="Audit the required provenance checks for the compatibility-named Block 2 robustness-over-summaries surface.",
        minimum_fields=("check", "passed", "detail"),
        artifact_state_location="block2_bounded_audit_manifest.json.artifact_state",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "A failed row is acceptable for scientific interpretation",
            "The block can run without Block 1 provenance",
        ),
    ),
    TaskAArtifactSpec(
        name="block2_manifest",
        filename="block2_bounded_audit_manifest.json",
        producer="write_block2_bundle",
        purpose="Freeze Block 2 provenance, scientific role, and claim scope for the compatibility-named robustness-over-summaries outputs.",
        minimum_fields=(
            "block",
            "scientific_role",
            "config_path",
            "config_fingerprint",
            "output_dir",
            "bundle_path",
            "block1_bundle_path",
            "block0_bundle_path",
            "block1_stage0_mapping_path",
            "block1_core_fit_dry_run_path",
            "block1_family_summary_path",
            "block1_source_community_summary_path",
            "block1_target_community_summary_path",
            "block1_confirmatory_family_comparison_path",
            "block1_exploratory_source_community_comparison_path",
            "block1_exploratory_target_community_comparison_path",
            "summary_path",
            "contract_path",
            "replicate_manifest_path",
            "family_robustness_path",
            "source_community_robustness_path",
            "target_community_robustness_path",
            "status",
            "artifact_state",
            "claim_scope",
            "summary_rows",
            "replicate_rows",
            "primary_routes",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(EVIDENCE_READY_STATE,),
        readiness_classification=EVIDENCE_READY_STATE,
        does_not_mean=(
            "Primary Block 1 evidence changed",
            "Canonical STRIDE emergence/disappearance was estimated",
        ),
    ),
    TaskAArtifactSpec(
        name="semisynthetic_manifest",
        filename="user-specified manifest filename",
        producer="write_semisynthetic_artifacts",
        purpose="Export deterministic semisynthetic patient-level benchmark rows.",
        minimum_fields=(
            "patient_id",
            "pair_family",
            "continuity_score",
            "source_residual_mass",
            "target_residual_mass",
        ),
        artifact_state_location="task_a_semisynthetic_contract.json.artifact_state",
        allowed_artifact_states=(CONTRACT_PASSED_STATE,),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Real-data Block 1 evidence is ready",
            "Real-data Block 0 passage exists",
        ),
    ),
    TaskAArtifactSpec(
        name="semisynthetic_contract",
        filename="task_a_semisynthetic_contract.json",
        producer="write_semisynthetic_artifacts",
        purpose="Freeze the deterministic same-marginals benchmark contract for semisynthetic exports.",
        minimum_fields=(
            "artifact_state",
            "n_patients",
            "seed",
            "same_marginals_pair_family",
            "stronger_continuity_score",
            "weaker_continuity_score",
        ),
        artifact_state_location="embedded field",
        allowed_artifact_states=(CONTRACT_PASSED_STATE,),
        readiness_classification=CONTRACT_PASSED_STATE,
        does_not_mean=(
            "Any real-data block already ran",
            "Block 2 is satisfied",
        ),
    ),
)


TASK_A_SURFACE_SPEC_BY_NAME: dict[str, TaskASurfaceSpec] = {
    spec.name: spec for spec in TASK_A_SURFACE_SPECS
}
TASK_A_EXECUTION_NODE_BY_NAME: dict[str, TaskAExecutionNode] = {
    node.name: node for node in TASK_A_EXECUTION_GRAPH
}
TASK_A_ARTIFACT_SPEC_BY_NAME: dict[str, TaskAArtifactSpec] = {
    spec.name: spec for spec in TASK_A_ARTIFACT_SPECS
}


__all__ = [
    "GRAPH_EXECUTION_STATUS",
    "READINESS_CLASSIFICATIONS",
    "SURFACE_EXECUTION_STATUS",
    "TASK_A_ARTIFACT_SPEC_BY_NAME",
    "TASK_A_ARTIFACT_SPECS",
    "TASK_A_EXECUTION_GRAPH",
    "TASK_A_EXECUTION_NODE_BY_NAME",
    "TASK_A_SURFACE_SPEC_BY_NAME",
    "TASK_A_SURFACE_SPECS",
    "TaskAArtifactSpec",
    "TaskAExecutionNode",
    "TaskASurfaceSpec",
]
