"""Calibration constants for Task A Block 3b internal Phase 3.

Task and purpose:
    Centralize calibration constants and interfaces used by the task-local
    `3B-1` and `3B-2` UOT baseline.

Relevant document anchors:
    - docs/task_A/spec.md §4.5.5-§4.5.6 and UOT calibration pseudocode
    - docs/task_A/block3/scientific_contract.md §4.3 and calibration closure notes

Expected inputs and outputs:
    Calibration consumes train-side patient profiles and returns one selected
    lambda. The target is train-side `mean(sum(min(x, y)))`; ties select the
    smaller lambda; boundary hits are diagnostics, not automatic failure.

Internal Phase 3 boundary:
    This module provides Task A Block 3 comparator calibration only. It is not
    part of the public STRIDE package and does not define a public runner,
    review workflow, or result-packet bridge.
"""
from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass

import numpy as np

LAMBDA_GRID: tuple[float, ...] = (0.05, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0)


@dataclass(frozen=True)
class UOTCalibrationResult:
    """Selected UOT penalty and train-side diagnostic metadata.

    Inputs are generated by `calibrate_uot_lambda`; outputs carry the selected
    lambda, overlap target, achieved mass by candidate, and whether selection
    hit the grid boundary. Boundary hits are diagnostic status, not failure.
    """

    selected_lambda: float
    target_overlap: float
    achieved_by_lambda: dict[float, float]
    absolute_error_by_lambda: dict[float, float]
    boundary_hit: bool


def lambda_grid() -> tuple[float, ...]:
    """Return the frozen train-side UOT lambda calibration grid."""

    return LAMBDA_GRID


def overlap_target(train_pairs: Sequence[tuple[np.ndarray, np.ndarray]]) -> float:
    """Return train-side mean shared endpoint overlap for UOT calibration."""

    overlaps = []
    for x, y in train_pairs:
        source = np.asarray(x, dtype=float)
        target = np.asarray(y, dtype=float)
        if source.shape != target.shape:
            raise ValueError("train pair x and y must have the same shape")
        if not np.isfinite(source).all() or not np.isfinite(target).all():
            raise ValueError("train pair x and y must contain finite values")
        if (source < 0.0).any() or (target < 0.0).any():
            raise ValueError("train pair x and y must be non-negative")
        overlaps.append(float(np.sum(np.minimum(source, target), dtype=float)))
    if not overlaps:
        raise ValueError("UOT calibration requires at least one train pair")
    # target_overlap is the train-side matched-mass target used to select lambda.
    return float(np.mean(overlaps))


def calibrate_uot_lambda(
    *,
    train_pairs: Sequence[tuple[np.ndarray, np.ndarray]],
    lambda_grid: Sequence[float] = LAMBDA_GRID,
    achieved_mass_fn: Callable[[float, Sequence[tuple[np.ndarray, np.ndarray]]], float] | None = None,
) -> UOTCalibrationResult:
    """Select the UOT lambda whose train-side matched mass best matches overlap.

    Inputs are train-side endpoint pairs, a positive candidate grid, and an
    optional achieved-mass callback used by tests or callers with precomputed
    plans. Output is calibration metadata; equal errors choose the smaller
    lambda and boundary hits remain diagnostic rather than non-estimable status.
    """

    pairs = tuple(train_pairs)
    # lambda_grid is the frozen internal candidate set for UOT calibration.
    candidates = tuple(float(candidate) for candidate in lambda_grid)
    if not candidates:
        raise ValueError("lambda_grid must be non-empty")
    if any((not np.isfinite(candidate) or candidate <= 0.0) for candidate in candidates):
        raise ValueError("lambda_grid values must be finite and positive")
    target = overlap_target(pairs)
    achieved_by_lambda: dict[float, float] = {}
    absolute_error_by_lambda: dict[float, float] = {}
    for candidate in candidates:
        achieved = (
            target
            if achieved_mass_fn is None
            else float(achieved_mass_fn(candidate, pairs))
        )
        achieved_by_lambda[candidate] = achieved
        absolute_error_by_lambda[candidate] = abs(achieved - target)
    selected = min(candidates, key=lambda candidate: (absolute_error_by_lambda[candidate], candidate))
    return UOTCalibrationResult(
        selected_lambda=selected,
        target_overlap=target,
        achieved_by_lambda=achieved_by_lambda,
        absolute_error_by_lambda=absolute_error_by_lambda,
        boundary_hit=selected in {candidates[0], candidates[-1]},
    )
